services:
  - type: web
    name: openai-server
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: API_KEY
        sync: false
      - key: PORT
        sync: false
